############
#
# Copyright (c) 2024 Maxim Yudayev and KU Leuven eMedia Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Created 2024-2025 for the KU Leuven AidWear, AidFOG, and RevalExo projects
# by Maxim Yudayev [https://yudayev.com].
#
# ############

project       : "AidFOG"
trial_type    : "test" # recommend "test" for testing and "real" data
subject_id    : 0 # UID of the subject
trial_id      : 0 # UID of the trial
duration_s    : null

print_status  : True
print_debug   : True


host_ip : "192.168.0.100"
is_master_broker: True

is_remote_kill: False
remote_kill_ip: null

remote_subscriber_ips: []
remote_publisher_ips: # IPs of Brokers to listen to for data on some of desired topics
  - "192.168.0.103"


logging_spec:
  stream_period_s     : 1
  
  stream_hdf5         : True
  stream_csv          : False
  stream_video        : True
  stream_audio        : False

  dump_csv            : False
  dump_hdf5           : False
  dump_video          : False
  dump_audio          : False

  video_codec_config_filepath : "resources/codecs/h264_qsv.yml" 
  video_codec_num_cpu : 1

  audio_format        : "wav" # currently only supports WAV


producer_specs:
  # Stream from one or more cameras.
  - class: "CameraStreamer"
    camera_mapping: # map camera names (usable as device names in the HDF5 file) to capture device indexes
      basler_north : "40478064"
      basler_east  : "40549960"
      basler_south : "40549975"
      basler_west  : "40549976"
    fps: 30
    resolution:
      - 1440
      - 2560
    camera_config_filepath: "resources/AidFOG/pylon_30fps_2K_40478064.pfs"


consumer_specs: []


pipeline_specs: []
