host_ip       : "10.244.21.115"
is_master_broker: True

remote_subscriber_ips: []
remote_publisher_ips: []

is_remote_kill: False
remote_kill_ip: null


logging_spec:
  stream_period_s     : 30
  
  stream_hdf5         : True
  stream_csv          : False
  stream_video        : False
  stream_audio        : False

  dump_csv            : False
  dump_hdf5           : False
  dump_video          : False
  dump_audio          : False

  video_codec_config_filepath : "resources/codecs/h264_qsv.yml" 
  video_codec_num_cpu : 1

  audio_format        : "wav" # currently only supports WAV


producer_specs:
  # Vicon capture system.
  - class: "ViconStreamer"
    device_mapping: 
      0 : 0
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
      11 : 11
      12 : 12
      13 : 13
      14 : 14
      15 : 15    


consumer_specs: []


pipeline_specs: []
