project       : "RevalExo"
trial_type    : "test" # recommend "test" for testing and "real" data
subject_id    : 0 # UID of the subject
trial_id      : 0 # UID of the trial
duration_s    : null

host_ip       : "127.0.0.1"
is_master_broker: True
remote_publisher_ips: []
remote_subscriber_ips: []

is_remote_kill: False
remote_kill_ip: null

is_expose_to_remote_sub : False
is_remote_kill : False

print_status  : True
print_debug   : True

>>>>>>> d419dbe (modified code for vicon)
logging_spec:
  stream_period_s     : 10
  
  stream_hdf5         : True
  stream_csv          : False
  # stream_video        : True
  stream_audio        : False

  dump_csv            : False
  dump_hdf5           : False
  dump_video          : False
  dump_audio          : False

  video_codec         : 'h264_qsv'
  video_codec_num_cpu : 1
  video_pix_format    : 'nv12'

  audio_format        : "wav" # currently only supports WAV


producer_specs:
    - class: "ViconStreamer"
      device_mapping: 
        0 : 0
        1 : 1
        2 : 2
        3 : 3
        4 : 4
        5 : 5
        6 : 6
        7 : 7
        8 : 8
        9 : 9
        10 : 10
        11 : 11
        12 : 12
        13 : 13
        14 : 14
        15 : 15   
    # - class: "CameraStreamer"
    #   camera_mapping: # map camera names (usable as device names in the HDF5 file) to capture device indexes
    #     basler_north : "40478064"
    #   fps: 30
    #   resolution:
    #     - 1440
    #     - 2560
    #   camera_config_filepath: "resources/AidFOG/pylon_30fps_2K.pfs" 
   

consumer_specs: []

pipeline_specs: []